#! /bin/bash

echo ' '
read -p 'Would you like to clear the previous map database? (y/n): ' ansinput

if [ “$ansinput” = “y” ]
then
 printf '\n Map deleted \n'
 rm -f ~/.ros/rtabmap.db

elif [ “$ansinput” = “n” ]
then
 printf '\n Map kept \n'

else
 echo 'Warning: Not an acceptable option. Choose (y/n).
         '
fi

echo ' '

read -p 'Enter target world destination or d for default: ' input_choice

if [ “$input_choice” = “d” ]
then
 x-terminal-emulator -e roslaunch slam_project world.launch world_file:=/home/abdulla/dev/online_courses/ROS/src/slam_project/worlds/kitchen_dining.world 2>/dev/null &

else
 x-terminal-emulator -e roslaunch slam_project world.launch world_file:=$input_choice 2>/dev/null &
fi

sleep 3 &&

echo ' '

read -p 'Enter controller k for keyboard or x for xbox joystick: ' input_choice

if [ “$input_choice” = “k” ]
then
x-terminal-emulator -e roslaunch slam_project teleop.launch 2>/dev/null &
else
x-terminal-emulator -e roslaunch slam_project xbox360_teleop.launch 2>/dev/null &
fi

sleep 3 &&

echo ' '
read -p 'Press any key to continue to mapping... ' -n1 -s

x-terminal-emulator -e roslaunch slam_project mapping.launch simulation:=true 2>/dev/null &
sleep 3 &&
x-terminal-emulator -e roslaunch slam_project rviz.launch 2>/dev/null

echo ' '
echo 'Script Completed'
echo ' '
